from __future__ import annotations

from ._version import __version__, __version_info__
from .client import MaxClient, create_client
from .config import MaxConfig, TransportConfig, AuthConfig, SessionConfig, create_config
from .enums import (
    TransportType,
    AuthType,
    ConnectionState,
    EventType,
    ErrorScope,
    MessageType,
    ChatType,
    UserStatus,
    DeviceType,
    UploadType,
)
from .types import (
    User,
    Profile,
    Contact,
    Session,
    Folder,
    Chat,
    ChatSettings,
    Member,
    InviteLinkInfo,
    JoinRequest,
    Message,
    Attachment,
    PhotoAttachment,
    VideoAttachment,
    VoiceAttachment,
    VideoNoteAttachment,
    FileAttachment,
    ContactAttachment,
    StickerAttachment,
    PollAttachment,
    LocationAttachment,
    Poll,
    PollOption,
    Reaction,
    ReactionInfo,
    ReactionCounter,
    ReadState,
    Photo,
    Video,
    Voice,
    VideoNote,
    Document,
    BaseFile,
    UploadResponse,
)
from .exceptions import (
    MaxError,
    ConfigError,
    AuthError,
    InvalidCredentialsError,
    TwoFactorRequiredError,
    SessionExpiredError,
    QRCodeExpiredError,
    ConnectionError,
    TransportError,
    ReconnectFailedError,
    APIError,
    RateLimitError,
    NotFoundError,
    ForbiddenError,
    ValidationError,
    ServerError,
    FileError,
    UploadError,
    DownloadError,
    DispatchError,
)
from .formatting import (
    MarkdownFormatter,
    bold,
    italic,
    underline,
    strikethrough,
    code,
    pre,
    link,
    mention,
    escape_markdown,
)
from .dispatch import Router, Dispatcher, Filter, CommandFilter, TextFilter

__all__ = [
    # Version
    "__version__",
    "__version_info__",
    # Client
    "MaxClient",
    "create_client",
    # Config
    "MaxConfig",
    "TransportConfig",
    "AuthConfig",
    "SessionConfig",
    "create_config",
    # Enums
    "TransportType",
    "AuthType",
    "ConnectionState",
    "EventType",
    "ErrorScope",
    "MessageType",
    "ChatType",
    "UserStatus",
    "DeviceType",
    "UploadType",
    # Types - User
    "User",
    "Profile",
    "Contact",
    "Session",
    "Folder",
    # Types - Chat
    "Chat",
    "ChatSettings",
    "Member",
    "InviteLinkInfo",
    "JoinRequest",
    # Types - Message
    "Message",
    "Attachment",
    "PhotoAttachment",
    "VideoAttachment",
    "VoiceAttachment",
    "VideoNoteAttachment",
    "FileAttachment",
    "ContactAttachment",
    "StickerAttachment",
    "PollAttachment",
    "LocationAttachment",
    "Poll",
    "PollOption",
    "Reaction",
    "ReactionInfo",
    "ReactionCounter",
    "ReadState",
    # Types - File
    "Photo",
    "Video",
    "Voice",
    "VideoNote",
    "Document",
    "BaseFile",
    "UploadResponse",
    # Exceptions
    "MaxError",
    "ConfigError",
    "AuthError",
    "InvalidCredentialsError",
    "TwoFactorRequiredError",
    "SessionExpiredError",
    "QRCodeExpiredError",
    "ConnectionError",
    "TransportError",
    "ReconnectFailedError",
    "APIError",
    "RateLimitError",
    "NotFoundError",
    "ForbiddenError",
    "ValidationError",
    "ServerError",
    "FileError",
    "UploadError",
    "DownloadError",
    "DispatchError",
    # Formatting
    "MarkdownFormatter",
    "bold",
    "italic",
    "underline",
    "strikethrough",
    "code",
    "pre",
    "link",
    "mention",
    "escape_markdown",
    # Dispatch
    "Router",
    "Dispatcher",
    "Filter",
    "CommandFilter",
    "TextFilter",
]